spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:38041/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=UluoclubsYVqNlgglREZQLCjWgSjCwsW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}